services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
